[package]
name = "tela"
version = "0.1.0"
edition = "2021"

[dependencies]
image = { version = "0.24", default-features = false, features = ["png"] }
wasm-bindgen = "0.2"

[lib]
path = "src/tela.rs"
crate-type = ["cdylib", "rlib"]
